name: MyPy

on:
  push:
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install mypy lxml html5lib pymongo-stubs pika-stubs
          pip install --upgrade --no-cache-dir --editable .

      - name: MyPy
        run: |

          echo "[mypy]" > mypy.ini

          for lib in glom flask_apispec apispec flask_caching flask_cors flask_restful celery neomodel neo4j sqlalchemy pymodm plumbum faker psutil jwt.exceptions passlib wrong; do
            echo "[mypy-${lib}.*]" >> mypy.ini
            
          done

          mypy --warn-redundant-casts --warn-unused-ignores --warn-unused-configs --warn-return-any --warn-unreachable --txt-report . --html-report . restapi/
          cat index.txt
