name: MyPy

on:
  push:
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install mypy lxml html5lib pymongo-stubs
          pip install --upgrade --no-cache-dir --editable .

      - name: MyPy
        run: |

          echo "[mypy]" > mypy.ini
          echo "[mypy-glom.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-flask_apispec.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-apispec.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-flask_caching.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-flask_cors.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-flask_restful.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-celery.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-neomodel.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-neo4j.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-sqlalchemy.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-plumbum.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          echo "[mypy-faker.*]" >> mypy.ini
          echo "ignore_missing_imports = True" >> mypy.ini
          mypy --warn-redundant-casts --warn-unused-ignores --warn-return-any --warn-unreachable --txt-report . --html-report . restapi/
          cat index.txt
