name: MyPy

on:
  push:
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install MyPy
        run: |
          sudo apt-get install --yes libgeos-dev
          python -m pip install --upgrade pip
          pip install \
            mypy \
            lxml \
            html5lib \
            types-requests \
            types-pytz \
            types-python-dateutil \
            types-certifi \
            types-click \
            types-PyYAML \
            types-orjson \
            types-redis \
            pika-stubs \
            celery-types \
            sqlalchemy-stubs
          pip install --upgrade --no-cache-dir --editable .

      - name: Run MyPy
        run: |

          echo "[mypy]" > mypy.ini
          echo "mypy_path = ./stubs" >> mypy.ini

          for lib in \
            flask_apispec \
            flask_caching \
            flask_cors \
            flask_sqlalchemy \
            flask_migrate \
            neo4j \
            neobolt \
            neomodel \
            psycopg2 \
            redbeat \
            geolite2 \
            plumbum \
            psutil \
            passlib \
            telethon \
            ; do
            echo "[mypy-${lib}.*]" >> mypy.ini
            echo "ignore_missing_imports = True" >> mypy.ini
            
          done

          mypy --disallow-untyped-defs --disallow-incomplete-defs --disallow-any-unimported --disallow-any-generics --check-untyped-defs --disallow-untyped-calls --warn-redundant-casts --warn-unused-ignores --warn-unused-configs --warn-return-any --warn-unreachable --txt-report report --html-report report restapi/ tests/
          cat report/index.txt

      - name: Save Report
        uses: actions/upload-artifact@v2
        with:
          name: mypy-report
          path: report
